import notifee, {
  AlarmType,
  AndroidImportance,
  AuthorizationStatus,
  EventType,
  TimestampTrigger,
  TriggerType,
} from '@notifee/react-native';
import { restOverBody } from './copy';
import { colors } from './theme';
import type { Notification } from '@notifee/react-native';

/**
 * The "time's up" alert, for when rest ends while the user is off in another
 * app — which is the normal case, since handing you your phone back is the
 * whole point of the rest period.
 *
 * It is *scheduled with the OS* rather than fired from a JS timer, because by
 * the time rest ends our JS thread is usually suspended behind whatever the
 * user is scrolling.
 */

const NOTIFICATION_ID = 'rest-over';

/**
 * Two channels, because an Android channel's sound cannot be changed after it
 * is created — the OS owns it from then on. Toggling sound therefore means
 * picking a different channel, not editing one.
 */
const CHANNELS = {
  loud: { id: 'rest-timer', name: 'Rest timer' },
  silent: { id: 'rest-timer-silent', name: 'Rest timer (silent)' },
} as const;

const channelReady: Partial<Record<'loud' | 'silent', Promise<string>>> = {};

async function ensureChannel(withSound: boolean): Promise<string> {
  const key = withSound ? 'loud' : 'silent';
  if (!channelReady[key]) {
    channelReady[key] = notifee.createChannel({
      ...CHANNELS[key],
      importance: withSound ? AndroidImportance.HIGH : AndroidImportance.DEFAULT,
      // `undefined` keeps the system default; `none` silences the channel.
      sound: withSound ? undefined : 'none',
      vibration: withSound,
    });
  }
  return channelReady[key]!;
}

export async function requestNotificationPermission(): Promise<boolean> {
  try {
    const settings = await notifee.requestPermission();
    return settings.authorizationStatus >= AuthorizationStatus.AUTHORIZED;
  } catch (err) {
    console.warn('[rest-timer] notification permission failed', err);
    return false;
  }
}

/** Schedule the "time's up" alert for `endsAt` (wall-clock ms). */
export async function scheduleRestOverNotification(
  endsAt: number,
  nextSet: number,
  totalSets: number,
  withSound: boolean = true,
) {
  try {
    const channelId = await ensureChannel(withSound);
    const trigger: TimestampTrigger = {
      type: TriggerType.TIMESTAMP,
      timestamp: Math.max(Date.now() + 1000, endsAt),
      // Android only. Notifee defaults triggers to WorkManager, which the OS
      // batches — far too loose for a 30-120s rest. AlarmManager with
      // ALLOW_WHILE_IDLE also escapes Doze, and needs no extra permission.
      // (SET_EXACT_* would be tighter but pulls in SCHEDULE_EXACT_ALARM, which
      // Android 14+ no longer grants freely. Inexact is fine here: the user is
      // actively scrolling, so the device isn't dozing.)
      alarmManager: { type: AlarmType.SET_AND_ALLOW_WHILE_IDLE },
    };
    await notifee.createTriggerNotification(
      {
        id: NOTIFICATION_ID,
        title: 'Time’s up!',
        // The set numbers earn their place: this is read on a lock screen, and
        // "which set am I on" is the one thing you can't see from there.
        //
        // The body rotates and the title doesn't, deliberately. A notification
        // whose title changes every time reads as a different app each time,
        // and this one has to be recognisable in a stack of them at a glance.
        // Seeded on the set number, so it varies through a workout and is
        // stable if the alert is rescheduled.
        body: restOverBody(nextSet, totalSets, nextSet),
        android: {
          channelId,
          // A white-on-transparent glyph, generated by `npm run icons`. Without
          // it Android silhouettes the full-colour launcher icon into a blob.
          smallIcon: 'ic_notification',
          // Tints the small icon and the app name in the shade.
          color: colors.accent,
          // `default` is the id Android special-cases as "open the app";
          // launchActivity spells out which one, so a cold start lands somewhere.
          pressAction: { id: 'default', launchActivity: 'default' },
          autoCancel: true,
        },
        // Omitting `sound` on iOS delivers the alert silently.
        ios: withSound ? { sound: 'default' } : {},
      },
      trigger,
    );
  } catch (err) {
    // A missing notification must never break the workout loop.
    console.warn('[rest-timer] could not schedule notification', err);
  }
}

/** Called when rest is skipped or the workout ends early. */
export async function cancelRestOverNotification() {
  try {
    await notifee.cancelTriggerNotification(NOTIFICATION_ID);
  } catch (err) {
    console.warn('[rest-timer] could not cancel notification', err);
  }
}

/* -------------------------------------------------------------------------
 * Tapping it
 * ---------------------------------------------------------------------- */

/**
 * A tap has to land the user back on the set they were about to do, not just
 * open the app — so the press is routed into the state machine rather than
 * left to the OS.
 *
 * Three arrival routes, all funnelled through one handler:
 *
 * - **Foreground** — the app is open and visible. Rare for this alert, but it
 *   happens if you're staring at the rest screen when it fires.
 * - **Background** — the usual case. The process is alive behind TikTok, the
 *   OS resumes it, and the event arrives before React re-renders.
 * - **Cold start** — the process was killed. `getInitialNotification` reports
 *   the tap that launched us.
 *
 * A press can therefore arrive before anything is listening, so one is held
 * and delivered to the first subscriber instead of being dropped.
 *
 * Delivering the same press twice is harmless and not worth de-duplicating:
 * the handler dispatches END_REST, which the reducer ignores unless the phase
 * is still `resting`. The second one lands on an already-active workout and
 * does nothing.
 */
type PressHandler = () => void;

const pressHandlers = new Set<PressHandler>();
let foregroundUnsubscribe: (() => void) | null = null;
let askedForInitial = false;
/** A press that landed before the app was listening. */
let heldPress = false;

const isOurs = (notification?: Notification) =>
  notification?.id === NOTIFICATION_ID;

function deliverPress() {
  if (pressHandlers.size === 0) {
    heldPress = true;
    return;
  }
  pressHandlers.forEach(handler => handler());
}

/**
 * Runs `handler` when the user taps the alert. Returns an unsubscribe.
 *
 * Safe to call more than once; the OS-level listeners are attached once for
 * the life of the process.
 */
export function onRestNotificationPress(handler: PressHandler): () => void {
  pressHandlers.add(handler);

  if (!foregroundUnsubscribe) {
    foregroundUnsubscribe = notifee.onForegroundEvent(({ type, detail }) => {
      if (type === EventType.PRESS && isOurs(detail.notification)) {
        deliverPress();
      }
    });
  }

  if (!askedForInitial) {
    askedForInitial = true;
    notifee
      .getInitialNotification()
      .then(initial => {
        if (initial && isOurs(initial.notification)) {
          deliverPress();
        }
      })
      .catch(err =>
        console.warn('[rest-timer] could not read the launch notification', err),
      );
  }

  if (heldPress) {
    heldPress = false;
    handler();
  }

  return () => {
    pressHandlers.delete(handler);
  };
}

/**
 * Registers the background tap listener.
 *
 * Must be called from `index.js` at module scope — notifee requires this to be
 * set up before React mounts, since the event can fire in a headless JS context
 * with no component tree at all.
 */
export function registerBackgroundNotificationHandler() {
  notifee.onBackgroundEvent(async ({ type, detail }) => {
    if (type === EventType.PRESS && isOurs(detail.notification)) {
      deliverPress();
    }
  });
}
