/**
 * Core domain types for the rest-timer workout loop.
 */

/** Which screen the workout is on. The phase *is* the navigation. */
export type Phase = 'setup' | 'active' | 'resting' | 'complete';

/**
 * A blockable app the user can pick.
 *
 * Phase 1: a hardcoded placeholder list.
 * Phase 2 (iOS): Apple's FamilyActivityPicker never tells us which apps were
 * chosen, so this list collapses into an opaque token. Keep consumers reading
 * `selectedAppIds.length` rather than the individual ids.
 */
/** The five apps that ship with a drawn brand mark. */
export type BrandId = 'tiktok' | 'instagram' | 'youtube' | 'x' | 'reddit';

export type BlockableApp = {
  id: string;
  name: string;
  /** Icon tint. Stands in for the real app icon, which iOS never gives us. */
  tint: string;
  /** Preset apps have a drawn logo; ones you add fall back to a monogram. */
  brand?: BrandId;
};

/** An app the user typed in themselves. */
export type CustomApp = {
  id: string;
  name: string;
  tint: string;
};

/**
 * A lift the user has saved, with its own numbers.
 *
 * Every exercise is independent: bench press resting 90s with TikTok blocked
 * has nothing to do with what tricep pulldowns are set to. Nothing outside
 * `defaults.selectedAppIds` — which only ever seeds a *new* exercise — is
 * shared between them.
 */
export type Exercise = {
  id: string;
  name: string;
  totalSets: number;
  /** Rest between sets, in seconds. */
  restSeconds: number;
  selectedAppIds: string[];
};

/**
 * The exercise currently being worked through.
 *
 * A snapshot taken when Start is tapped, not a live reference: editing the
 * saved exercise mid-workout must not move the goalposts underneath the set
 * you're on, and the summary screen needs to describe the workout that
 * happened rather than whatever the card says afterwards.
 */
export type WorkoutConfig = {
  exerciseName: string;
  totalSets: number;
  restSeconds: number;
  selectedAppIds: string[];
};

/**
 * App-wide preferences, edited on the Settings tab.
 *
 * Sets and rest are deliberately *not* here — those live on each exercise.
 * What's left is a genuine preference (sound) plus the app list, which does
 * double duty: it's the pool every exercise picks from, and the selection
 * seeds each newly created exercise.
 */
export type AppDefaults = {
  /** Ticked on a new exercise. Changing it never touches existing ones. */
  selectedAppIds: string[];
  /** Whether the rest-over notification makes a sound. */
  soundEnabled: boolean;
  /** Apps added by hand, on top of the five presets. */
  customApps: CustomApp[];
};

/**
 * Running totals for the whole app session — every workout since launch.
 *
 * Explicitly *not* a history: nothing here is written to storage, so it starts
 * at zero on every launch. That's the honest scope for a stats row in an app
 * with no accounts and no backend, and it's why the card is labelled "this
 * session" rather than "today" — a day would imply the numbers survive a
 * restart, which they don't.
 */
export type SessionTotals = {
  setsCompleted: number;
  /** Seconds the apps were locked, summed across workouts. */
  lockedSeconds: number;
  /** Workouts that got at least one set done. */
  workoutsFinished: number;
};

export type WorkoutState = {
  phase: Phase;
  session: SessionTotals;
  /** The saved list, in the order they were added. */
  exercises: Exercise[];
  /** Snapshot of the exercise being run. Meaningless while phase is 'setup'. */
  config: WorkoutConfig;
  defaults: AppDefaults;
  /** 1-based index of the set the user is on / just finished. */
  currentSet: number;
  setsCompleted: number;
  /** Wall-clock ms timestamp when the current rest period started. Null off-rest. */
  restStartedAt: number | null;
  /** Wall-clock ms timestamp when the current rest period ends. Null off-rest. */
  restEndsAt: number | null;
  /** Total seconds actually spent resting, accumulated across the workout. */
  totalRestSeconds: number;
  /** Wall-clock ms when the current locked stretch began. Null while unlocked. */
  lockedSince: number | null;
  /**
   * Total seconds the apps were locked this workout — the time the phone was
   * out of reach. Shown on the summary as "time reclaimed".
   *
   * Session-only, like everything else about a workout: it is reset by
   * START_WORKOUT and never persisted.
   */
  totalLockedSeconds: number;
  /** True whenever the blocker should be shielding the user's apps. */
  appsLocked: boolean;
};

/** What gets written to storage. See src/state/storage.ts. */
export type SavedState = {
  defaults: AppDefaults;
  exercises: Exercise[];
};

export type WorkoutAction =
  /* --- The exercise list ------------------------------------------------ */
  /** `id` is generated by the caller, so the reducer stays pure. */
  | { type: 'ADD_EXERCISE'; id: string; name: string }
  | { type: 'REMOVE_EXERCISE'; id: string }
  | { type: 'SET_EXERCISE_SETS'; id: string; sets: number }
  | { type: 'SET_EXERCISE_REST'; id: string; seconds: number }
  | { type: 'TOGGLE_EXERCISE_APP'; id: string; appId: string }
  | { type: 'DELETE_ALL_EXERCISES' }
  /* --- Settings --------------------------------------------------------- */
  | { type: 'TOGGLE_DEFAULT_APP'; appId: string }
  | { type: 'SET_SOUND_ENABLED'; enabled: boolean }
  | { type: 'ADD_CUSTOM_APP'; name: string }
  | { type: 'REMOVE_CUSTOM_APP'; appId: string }
  /* --- The workout loop -------------------------------------------------- */
  /** Runs one saved exercise. Ignored if the id isn't in the list. */
  | { type: 'START_WORKOUT'; id: string; now: number }
  /** User tapped "Done with set" — begins rest, or completes the workout. */
  | { type: 'FINISH_SET'; now: number }
  /** Rest ran out, or the user tapped "Skip rest". */
  | { type: 'END_REST'; now: number }
  | { type: 'END_WORKOUT'; now: number }
  | { type: 'NEW_WORKOUT' }
  /**
   * Exercises and preferences restored from storage on launch.
   *
   * Deliberately narrower than the whole state: restoring a saved *workout*
   * would resume a session from days ago, with a `restEndsAt` long past.
   */
  | { type: 'HYDRATE'; saved: SavedState };
